/* Add your project URL and anon key from Supabase Settings > API. */
const SUPABASE_URL = 'https://jkxmwmnffoftjegrccrk.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_kcqMOnlJzL4VhBn4CDhXVw_YKHsljb9';
const configured = !SUPABASE_URL.includes('PASTE_') && !SUPABASE_ANON_KEY.includes('PASTE_');
const db = configured ? supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
let profile, programs=[], scholars=[], submissions=[];
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=s=>`<span class="badge ${esc(s).replaceAll(' ','.')}">${esc(s)}</span>`;
function flash(message,error=false){$('#flash').innerHTML=message?`<p class="${error?'form-error':''}">${esc(message)}</p>`:'';setTimeout(()=>$('#flash').innerHTML='',4000)}

$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();if(!db)return $('#authError').textContent='Configure SUPABASE_URL and SUPABASE_ANON_KEY in app.js first.';const {error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});$('#authError').textContent=error?.message||'';});
$('#logoutBtn').onclick=()=>db.auth.signOut();
async function boot(){if(!db)return;const {data:{session}}=await db.auth.getSession();if(!session){$('#authView').hidden=false;$('#appView').hidden=true;return}const {data,error}=await db.from('profiles').select('*').eq('id',session.user.id).single();if(error||!['admin','staff'].includes(data.role)){await db.auth.signOut();$('#authError').textContent='This account is not authorized as staff or admin.';return}profile=data;$('#authView').hidden=true;$('#appView').hidden=false;$('#userName').textContent=data.full_name;$('#profileInitial').textContent=data.full_name[0].toUpperCase();await loadData();}
async function loadData(){const [p,s,g]=await Promise.all([db.from('scholarship_programs').select('*').order('program_name'),db.from('scholars').select('*, scholarship_programs(program_name)').order('full_name'),db.from('grade_submissions').select('*, scholars(full_name, scholarship_id, scholarship_programs(program_name,required_gwa,min_units,allow_failing_grade))').order('submitted_at',{ascending:false})]);programs=p.data||[];scholars=s.data||[];submissions=g.data||[];renderAll()}
function renderAll(){renderStats();renderScholars();renderPrograms();renderSubmissions();renderCompliance();$('#scholarFilter').innerHTML='<option value="">All programs</option>'+programs.map(p=>`<option value="${p.id}">${esc(p.program_name)}</option>`).join('')}
function renderStats(){const verified=submissions.filter(x=>x.submission_status==='Verified'), compliant=verified.filter(x=>x.compliance_status==='Compliant'), deficient=verified.filter(x=>x.compliance_status==='With Deficiency');const vals=[['Total scholars',scholars.length],['Pending verification',submissions.filter(x=>x.submission_status==='Pending').length],['Verified submissions',verified.length],['Compliant',compliant.length],['With deficiency',deficient.length]];$('#stats').innerHTML=vals.map(x=>`<article class="stat"><p>${x[0]}</p><strong>${x[1]}</strong></article>`).join('');$('#recentRows').innerHTML=submissions.slice(0,5).map(x=>`<tr><td>${esc(x.scholars?.full_name)}</td><td>${esc(x.academic_year)} · ${esc(x.semester)}</td><td>${x.gwa}</td><td>${badge(x.submission_status)}</td><td><button class="text-btn goto" data-page="submissions">View</button></td></tr>`).join('')||empty(5)}
function renderScholars(){let rows=scholars.filter(s=>(`${s.student_id} ${s.full_name}`.toLowerCase().includes($('#scholarSearch').value.toLowerCase()))&&(!$('#scholarFilter').value||s.scholarship_id===$('#scholarFilter').value)&&(!$('#statusFilter').value||s.status===$('#statusFilter').value));$('#scholarRows').innerHTML=rows.map(s=>`<tr><td>${esc(s.student_id)}</td><td><b>${esc(s.full_name)}</b></td><td>${esc(s.scholarship_programs?.program_name)}</td><td>${esc(s.degree_program)} / ${s.year_level}</td><td>${badge(s.status)}</td><td><button class="text-btn edit-scholar" data-id="${s.id}">Edit</button></td></tr>`).join('')||empty(6)}
function renderPrograms(){$('#programCards').innerHTML=programs.map(p=>`<article class="program-card"><h2>${esc(p.program_name)}</h2><div class="rule"><span>Required GWA</span><b>≤ ${p.required_gwa}</b></div><div class="rule"><span>Minimum units</span><b>${p.min_units}</b></div><div class="rule"><span>Failing grade</span><b>${p.allow_failing_grade?'Allowed':'Not allowed'}</b></div><div class="rule"><span>Availability</span>${badge(p.active?'Active':'Inactive')}</div></article>`).join('')||'<p>No programs yet. Add your first scholarship program.</p>'}
function renderSubmissions(){$('#submissionRows').innerHTML=submissions.map(x=>`<tr><td><b>${esc(x.scholars?.full_name)}</b></td><td>${esc(x.academic_year)} / ${esc(x.semester)}</td><td>${x.gwa}</td><td>${x.units_enrolled}</td><td>${badge(x.submission_status)}</td><td>${x.compliance_status?badge(x.compliance_status):'—'}</td><td>${x.submission_status==='Pending'?`<button class="primary verify" data-id="${x.id}">Verify</button>`:'—'}</td></tr>`).join('')||empty(7)}
function renderCompliance(){const rows=submissions.filter(x=>x.submission_status==='Verified');$('#complianceRows').innerHTML=rows.map(x=>`<tr><td>${esc(x.scholars?.full_name)}</td><td>${esc(x.scholars?.scholarship_programs?.program_name)}</td><td>${esc(x.academic_year)} / ${esc(x.semester)}</td><td>${badge(x.compliance_status)}</td><td>${esc(x.deficiency_reason||'All requirements met')}</td></tr>`).join('')||empty(5)}
function empty(n){return `<tr><td colspan="${n}" style="text-align:center;color:#6d7774;padding:28px">No records found.</td></tr>`}
document.addEventListener('click',e=>{let p=e.target.dataset.page;if(p){document.querySelectorAll('.page,.nav').forEach(x=>x.classList.remove('active'));$(`#${p}Page`).classList.add('active');$(`.nav[data-page="${p}"]`)?.classList.add('active');$('#pageTitle').textContent={'dashboard':'Dashboard','scholars':'Scholars','programs':'Scholarship programs','submissions':'Grade submissions','compliance':'Compliance'}[p];$('#pageKicker').textContent=p.toUpperCase();}if(e.target.id==='newProgramBtn')openProgram();if(e.target.id==='newScholarBtn')openScholar();if(e.target.id==='newSubmissionBtn')openSubmission();if(e.target.classList.contains('edit-scholar'))openScholar(scholars.find(s=>s.id===e.target.dataset.id));if(e.target.classList.contains('verify'))verify(e.target.dataset.id)});
['scholarSearch','scholarFilter','statusFilter'].forEach(id=>$('#'+id).addEventListener('input',renderScholars));
const field=(label,name,type='text',value='',opts=[],full=false)=>`<label class="${full?'full':''}">${label}${type==='select'?`<select name="${name}" required>${opts.map(o=>`<option value="${esc(o.value)}" ${String(o.value)===String(value)?'selected':''}>${esc(o.label)}</option>`).join('')}</select>`:`<input name="${name}" type="${type}" value="${esc(value)}" required>`}</label>`;
function open(title,fields,handler){$('#modalTitle').textContent=title;$('#modalFields').innerHTML=fields;$('#modalError').textContent='';$('#modal').showModal();$('#modalForm').onsubmit=async e=>{e.preventDefault();$('#saveModal').disabled=true;try{await handler(Object.fromEntries(new FormData(e.target)));$('#modal').close();await loadData();flash('Saved successfully.')}catch(err){$('#modalError').textContent=err.message}finally{$('#saveModal').disabled=false}}}
function openProgram(){open('Add scholarship program',field('Program name','program_name','text','',[],true)+field('Required GWA (1.00–5.00)','required_gwa','number','',[],false)+field('Minimum enrolled units','min_units','number','',[],false)+field('Failing grades policy','allow_failing_grade','select','false',[{value:'false',label:'Not allowed'},{value:'true',label:'Allowed'}]),async d=>{if(+d.required_gwa<1||+d.required_gwa>5)throw Error('GWA must be between 1.00 and 5.00.');const {error}=await db.from('scholarship_programs').insert({...d,required_gwa:+d.required_gwa,min_units:+d.min_units,allow_failing_grade:d.allow_failing_grade==='true',active:true});if(error)throw error})}
function openScholar(s={}){const opts=[{value:'',label:'Select program'}].concat(programs.filter(p=>p.active).map(p=>({value:p.id,label:p.program_name})));open(s.id?'Edit scholar':'Add scholar',field('Student ID','student_id','text',s.student_id,'',true)+field('Full name','full_name','text',s.full_name,'',true)+field('Degree program','degree_program','text',s.degree_program)+field('Year level','year_level','number',s.year_level)+field('Scholarship program','scholarship_id','select',s.scholarship_id,opts,true)+field('Current status','status','select',s.status||'Active',['Active','Pending Submission','Compliant','With Deficiency','Probationary'].map(x=>({value:x,label:x})),true),async d=>{let q=s.id?db.from('scholars').update({...d,year_level:+d.year_level}).eq('id',s.id):db.from('scholars').insert({...d,year_level:+d.year_level});const {error}=await q;if(error)throw error})}
function openSubmission(){const opts=[{value:'',label:'Select scholar'}].concat(scholars.map(s=>({value:s.id,label:`${s.student_id} — ${s.full_name}`})));open('Submit semester grades',field('Scholar','scholar_id','select','',opts,true)+field('Academic year','academic_year','text','2026-2027')+field('Semester','semester','select','1st Semester',[{value:'1st Semester',label:'1st Semester'},{value:'2nd Semester',label:'2nd Semester'},{value:'Summer',label:'Summer'}])+field('GWA (1.00–5.00)','gwa','number','')+field('Units enrolled','units_enrolled','number','')+field('Failed subjects','failed_subjects','number','0')+field('Incomplete subjects','incomplete_subjects','number','0'),async d=>{for(const k of ['units_enrolled','failed_subjects','incomplete_subjects'])if(+d[k]<0)throw Error('Counts cannot be negative.');if(+d.gwa<1||+d.gwa>5)throw Error('GWA must be between 1.00 and 5.00.');const {error}=await db.from('grade_submissions').insert({...d,gwa:+d.gwa,units_enrolled:+d.units_enrolled,failed_subjects:+d.failed_subjects,incomplete_subjects:+d.incomplete_subjects,submission_status:'Pending'});if(error)throw error})}
async function verify(id){const x=submissions.find(s=>s.id===id), rule=x.scholars?.scholarship_programs;if(!rule)return flash('Scholar does not have an active scholarship rule.',true);const failures=[];if(x.gwa>rule.required_gwa)failures.push(`GWA ${x.gwa} is above required ${rule.required_gwa}`);if(x.units_enrolled<rule.min_units)failures.push(`Units below required ${rule.min_units}`);if(!rule.allow_failing_grade&&x.failed_subjects>0)failures.push('Failing grades are not allowed');if(x.incomplete_subjects>0)failures.push('Has incomplete subject(s)');const result=failures.length?'With Deficiency':'Compliant';const {error}=await db.from('grade_submissions').update({submission_status:'Verified',verified_by:profile.id,verified_at:new Date().toISOString(),compliance_status:result,deficiency_reason:failures.join('; ')||null}).eq('id',id);if(error)return flash(error.message,true);const {error:se}=await db.from('scholars').update({status:result}).eq('id',x.scholar_id);if(se)return flash(se.message,true);await loadData();flash(`Submission verified: ${result}.`)}
$('#closeModal').onclick=$('#cancelModal').onclick=()=>$('#modal').close();if(configured)db.auth.onAuthStateChange(()=>boot());boot();
